#!/usr/bin/env php
<?php

use Psy\Shell;
use Psy\Configuration;
use Illuminate\Support\Collection;
use Illuminate\Api\Resource\Model;
use Illuminate\Api\Resource\Parameter;
use Symfony\Component\VarDumper\Caster\Caster;

require __DIR__ . '/../vendor/autoload.php';

(new Dotenv\Dotenv(__DIR__))->load();

// Shortcut to alegra class
spl_autoload_register(function ($className) {
   static $wrappers = [
      'Alegra',
      'Alegra\\Support'
   ], $queue = [];
   foreach ($wrappers as $wrapClass) {
       $wrapClass = $wrapClass . '\\'. $className;
       if (isset($queue[$wrapClass])) {
           continue;
       }
       $queue[$wrapClass] = true;
       if (class_exists($wrapClass)) {
           unset($queue[$wrapClass]);
           return class_alias($wrapClass, $className);
       }
   }
}, true);

Api::auth($_ENV['API_USER'], $_ENV['API_KEY']);

$casterToArray = function ($model) {
    $results = [];
    foreach ($model->toArray() as $key => $value) {
        $results[Caster::PREFIX_VIRTUAL . $key] = $value;
    }
    return $results;
};

$casterCollection = function (Collection $collection) {
    return [
        Caster::PREFIX_VIRTUAL.'all' => $collection->all(),
    ];
};

$config = new Configuration;
$config->getPresenter()->addCasters([
    Collection::class => $casterCollection,
    Model::class => $casterToArray,
    Parameter::class => $casterToArray
]);
$shell = new Shell($config);
$shell->run();
